#! /bin/sh

#euclidrc
#this gets run by euclid at startup
#it must be named $XDG_CONFIG_HOME/euclid-wm/euclidrc or if XDG_CONFIG_HOME is undefined 
#$HOME/.config/euclid-wm/euclidrd

#if you don't get a cursor at startup, and this bothers you, uncomment this
#xsetroot -cursor_name left_ptr &

#If you use dzen you should define the reserverd_top or  _bottom  keywords in euclid-wm.conf
#BTW, dzenscript doesn't actually exist, you have to make your own 
#~/.config/euclid-wm/dzenscript | dzen2 -p &

#if you use it:
#xscreensaver &

#This let's you do root stuff without being root (e.g., mount internal hdds in your file manager)
#/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

#this makes your windows perty
#xfsettingsd &
#or if you prefer it: 
#gnome-settings-daemon &

#If you have the patched version of stalonetray you can activate it here
#stalonetray --icon-size=20 --kludges=force_icons_size &

#and then  put a couple things in it
#nm-applet &
#gnome-sound-applet &

