.TH EUCLID 1 30-6-2010
.SH NAME
euclid-wm \- A highly flexible, minimal, dynamic, tiling window manager
.SH SYNOPSIS
.B euclid-wm
.SH DESCRIPTION
.B euclid  
.I (euclid-wm)
aims to be a highly flexible tiling window manger, which allows easy management of large collections of windows entirely from the keyboard.
.SH USAGE
.SS Basic Concepts
Euclid's state can be described as:
.IP * A set of 
.B views.
These are aranged in a series. Up to 9 of them are numbered. They are composed of a set of visible windows (arranged in 
.B tracks
) and minimized windows (stored in a 
.B stack
).
.IP * 
.B tracks
are either rows or collumns (the orientation can be toggled at runtime), that contain visible windows. 
.IP * the
.B stack
is a set of minimized windows, associated with a view, which can be viewed at the bottom of the screen in the form of a box containing their titles.

All bindings are prefaced by Meta (M, generally alt).

.SS Starting Programs
.IP
.B M + <enter>
\- start run dialogue (dmenu). NB: this takes keyboard focus as long as it is open; Once it is opened you must either select a command (with enter) or exit the dialog (with esc).
.IP 
.B M + <shift> + <enter>
\- start x-terminal-emulator

.SS Basic Window Manipulation
.IP  
.B M + h/j/k/l 
\- move focus left/down/up/right
.IP
.B M + H/J/K/L 
\- move focused window left/down/up/right
.IP
.B M + u/i/o/p
\- resize window: move lower right corner left/down/up/right
.IP
.B M + <esc>
\- close currently focused window
.IP
.B M + <shift> + <esc>
\- kill window (for unresponsive programs)

.SS The Stack
The stack maintins its own focus; The currently focused item can be identified by its blue color. 
.IP 
.B M + <space>
\- Toggle the stack's visibility 
.IP 
.B M + .
\- Move the currently focused window to the stack (i.e., minimize it)
.IP
.B M + ,
\- Move the currently focused stack item to the main area (i.e., restore it)
.IP
.B M + ;/'
\ - Move stack focus up/down

.SS Manipulating Views
.IP
.B M + n/m
\- Move to the previous/next view
.IP
.B M + N/M
\- Move currently focused window to the previous/next view
.IP
.B M + 1-9
\- Move to the 1-9th view
.IP
.B M + <shift> + 1-9
\- Move the currently focused window to the 1-9th view

A note on the order and numbering of views:
The enumeration is not strictly accurate; View 9 may not be the 9th view. Specifically, once a view is assigned a number it reatins that number regardless of where it actually falls in the list of views. This is so that accessing views based on their number remains consistent. 

The first view, created when euclid starts, is view 1; Going to the previous view makes a new view, but view 1 remains the original one, even though by counting it is now actually the second. Likewise, if one starts on view 1, and goes to view 9, view 9 remains view 9, even though it may actually be the second view. However, numbered views are always in order. So if one starts with view 1 and creates view 9, then creates view 8, view 8 will be placed between views 1 and 9.  

.SS Other 
.IP
.B M + <shift> + <space>
\- Change to fullscreen mode
.IP 
.B M + <tab> 
\- toggle the orientation of the tracks (vertical or horizontal layout)
.IP 
.B M + Q 
\- quit euclid.  
.SH FILES
.IP
On startup euclid will look for 
.I $XDG_CONFIG_HOME/euclid-wm/euclid-wm.conf 
If $XDG_CONFIG_HOME is not defined it will look for 
.I $HOME/.config/euclid-wm/euclid-wm.conf
If euclid-wm.conf is found, euclid will override its default settings with those found in the file. 
A sample config file 
.I euclid-wm.conf.sample 
should have come with euclid and can be installed by the makefile by running 
.I make install_conf 
as a regular user. 
At startup euclid will also (try to) run the script
.I euclidrc
in the same directory. This is meant as a place for the user to add any commands he would like run at startup.  
  
.SH BUGS (AND TODO AND MISSING FEATURES)
.SS TODO:
.IP 
Improve fullscreen awareness. Fullscreen is mostly working. However, windows that start in fullscreen (as opposed to switching to fullscreen once mapped) will not be automatically switched to fullscreen (e.g., flashplayer). The work-around at the moment is to put the view into fullscreen mode before launching the fullscreen window. 

Applications that have seperate fullscreen UIs, may continue to display their fullscreen UI if they are taken out of fullscreen by using the euclid keybinding instead of their own native mechanism for switching. (This can be worked around by just using their native mechanism.) 

.SS MISSING FEATURES (may or may not be implemented):
.IP 
Multiscreen awareness. 


.SS CURRENT issues and reporting: 
.IP
Please go to http://code.google.com/p/euclid-wm/issues/list to see the most recent set of known issues, to report new bugs, or request features. 
