#! /bin/sh

if [ ! `which dmenu_run` ]; then echo "WARNING: dmenu_run not found, you should install dmenu before running euclid-wm"; fi
if [ ! `which x-terminal-emulator` ]; then echo "WARNING: x-terminal-emulator not found, you should define it before running euclid-wm"; fi
if [ ! `which x-terminal-emulator` ] && [ ! `which dmenu_run` ]; then echo "ERROR: Neither x-terminal-emulator, nor dmenu_run can be found. Without at least one of these you will not be able to run anything once you start euclid-wm.Please install one of these and try again. Aborting install."; exit 1; fi
cp ./euclid-wm /usr/bin/euclid-wm
cp ./start-euclid /usr/bin/start-euclid
cp ./euclid.desktop /usr/share/xsessions/euclid.desktop
cp ./euclid.1 /usr/share/man/man1/euclid-wm.1
