#! /bin/bash

#find XDG_CONFIG_HOME
if [ -n `echo -n $XDG_CONFIG_HOME` ]; then
	echo "not def"
	CONFDIR=$HOME/.config/euclid-wm
else 
	echo "Def"
	CONFDIR=$XDG_CONFIG_HOME/euclid-wm
fi

if [ ! -e $CONFDIR/euclid-wm.conf ]; then
	install -m600 -D /usr/share/euclid-wm/euclid-wm.conf $CONFDIR/euclid-wm.conf
fi

if [ ! -e $CONFDIR/euclidrc ]; then
	install -m700 -D /usr/share/euclid-wm/euclidrc $CONFDIR/euclidrc
fi

$CONFDIR/euclidrc 

euclid-wm
